version: '3'

services:
  server:
    build: server/
    depends_on:
      - 'database'
    ports:
      - '3000:3000'

  database:
    image: mysql:8.0.23
    restart: always
    environment: 
      MYSQL_DATABASE: 'ratings'
      MYSQL_ALLOW_EMPTY_PASSWORD: 'true'
    volumes:
      - db_data:/var/lib/mysql
